### PR TITLE
Compat with Rails 5

### PR DESCRIPTION
**Pull request by danielfarrell**
Will invalidate sessions when it roles out.

### CODE REVIEW

**Comment by kevinrood** [comment]
All good here. Just to confirm, our use of this gem will go away when both apps are on Rails 5? (I think the answer was yes already).

Please merge this whenever it suits your purpose.

**Comment by danielfarrell** [comment]
yep, seems like we can/will need to use the mongo_session_store gem in rails 5.

**Comment by freaktoe** [comment]
Hey guys!  Looks like I still have access here but don't think I should.

**Comment by danielfarrell** [comment]
Hey @freaktoe, this is an open source fork of a repo.  You might need to un-watch it so you don't see any info from it anymore.  I don't see you having any permissions to it though.  That help?

**Comment by sethwenzel** [comment]
I also see this. And I also don’t think I should...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
